# Generated by Django 3.2.8 on 2021-11-21 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepositApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('depoMoney', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
