# Generated by Django 3.2.8 on 2021-11-21 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('income', models.IntegerField()),
                ('mobile_no', models.BigIntegerField(blank=True, error_messages={'unique': 'The mobile number you entered is already register.Pls try again!'}, unique=True)),
                ('address', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
